include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
    avoid_print: false
    use_build_context_synchronously: false
    prefer_final_fields: false
    dangling_library_doc_comments: false
    unnecessary_brace_in_string_interps: false
